name: hookup4u
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  country_code_picker: ^1.2.3
  pin_code_fields: ^2.3.0+3
  flutter_swiper: ^1.1.6
  intl: ^0.16.1

  location: ^3.0.2
  geocoder: ^0.2.1
  image_picker: ^0.6.3+4
  image_cropper: ^1.2.1
  path_provider:
  cached_network_image: ^2.0.0
  share: ^0.6.3+6
  flutter_webview_plugin: ^0.3.11
  in_app_purchase: ^0.3.4
  rflutter_alert: ^1.0.3
  agora_rtc_engine: 1.0.5
  permission_handler: ^3.0.0
  flutter_ringtone_player: ^2.0.0
  shimmer: ^1.1.1
  apple_sign_in: ^0.1.0
  url_launcher: ^5.5.0
  flutter_mapbox_autocomplete: ^1.0.4

  cupertino_icons: ^0.1.2
  easy_localization: ^2.1.0

  firebase_messaging: ^6.0.13
  firebase_auth: 0.15.4
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+2
  firebase_core: 0.4.4
  firebase_crashlytics: ^0.1.3+3

  awesome_dialog: ^2.1.1
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "asset/Icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - asset/
   - asset/Icon/
   - asset/auth/
   - asset/translation/
   - asset/images/
